[project]
name = "agent-cloud-dockerize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.16.1",
    "nbconvert>=7.16.6",
    "openai>=1.82.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
